# Generated by Django 3.1.4 on 2020-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('no_of_rooms', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=200)),
                ('room_length', models.CharField(max_length=200)),
                ('room_width', models.CharField(max_length=200)),
                ('room_height', models.CharField(max_length=200)),
                ('room_capacity', models.CharField(max_length=200)),
                ('available_capacity', models.CharField(max_length=200)),
                ('product_already_stored', models.CharField(max_length=200)),
                ('refrigerant', models.CharField(max_length=200)),
                ('room_temperature', models.CharField(max_length=200)),
                ('relative_humidity', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
