# Generated by Django 3.1.4 on 2020-12-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201205_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('crop_stage', models.CharField(max_length=200)),
                ('total_crop_quantity', models.CharField(max_length=200)),
                ('daily_loading', models.CharField(max_length=200)),
                ('required_temperature', models.CharField(max_length=200)),
                ('required_relative_humidity', models.CharField(max_length=200)),
                ('duration_of_storage', models.CharField(max_length=200)),
                ('pick_up_location', models.CharField(max_length=200)),
                ('drop_off_location', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crop'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
